### ISSUE TITLE
Territory Flag Exception

### ISSUE THREAD

**Issue by zunath** [zunath/Freescape_JVM#138]
Might be DM-related.

Unable to initialize conversation: TerritoryFlag
Exception:
javax.persistence.PersistenceException: org.hibernate.HibernateException: Unable to call class Entities.TerritoryStructureCountEntity constructor
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1423)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1463)
        at Data.DataContext.executeSQLSingle(DataContext.java:163)
        at Data.Repository.StructureRepository.GetNumberOfStructuresInTerritory(StructureRepository.java:171)
        at Conversation.TerritoryFlag.BuildMainPageHeader(TerritoryFlag.java:134)
        at Conversation.TerritoryFlag.Initialize(TerritoryFlag.java:125)
        at Dialog.DialogBase.SwitchConversation(DialogBase.java:160)
        at Conversation.BuildingExit.HandleMainPageResponses(BuildingExit.java:82)
        at Conversation.BuildingExit.DoAction(BuildingExit.java:66)
        at Dialog.ActionTaken.runScript(ActionTaken.java:36)
        at Common.EventReceiver.event(EventReceiver.java:19)
        at org.nwnx.nwnx2.jvm.Scheduler.event(Unknown Source)
        Suppressed: org.hibernate.TransactionException: Transaction was marked for rollback only; cannot commit
                at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:228)
                at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
                at Data.DataContext.close(DataContext.java:205)
                at Data.Repository.StructureRepository.GetNumberOfStructuresInTerritory(StructureRepository.java:173)
                ... 8 more
Caused by: org.hibernate.HibernateException: Unable to call class Entities.TerritoryStructureCountEntity constructor
        at org.hibernate.loader.custom.ConstructorResultColumnProcessor.extract(ConstructorResultColumnProcessor.java:65)
        at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:83)
        at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:60)
        at org.hibernate.loader.custom.CustomLoader.getResultColumnOrRow(CustomLoader.java:409)
        at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:771)
        at org.hibernate.loader.Loader.processResultSet(Loader.java:1001)
        at org.hibernate.loader.Loader.doQuery(Loader.java:959)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:351)
        at org.hibernate.loader.Loader.doList(Loader.java:2702)
        at org.hibernate.loader.Loader.doList(Loader.java:2685)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2517)
        at org.hibernate.loader.Loader.list(Loader.java:2512)
        at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:335)
        at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2162)
        at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1011)
        at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:152)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
        ... 11 more
Caused by: java.lang.IllegalArgumentException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.hibernate.loader.custom.ConstructorResultColumnProcessor.extract(ConstructorResultColumnProcessor.java:61)
        ... 27 more

**Comment by Cablefish1** [comment]
Yeah. I jumped around in the areas and touched the doors. I guess doing stuff thats not supposed to happen is going to break stuff.
